version: "2.1"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    build: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 3
